### PR TITLE
feat: return all signers

### PR DESCRIPTION
**Pull request by highskore**
This is a fix for #3, removes erc1271 early revert and recovers all signers. Theres still some open questions though:

1. do we still need the requiredSignatures param?
2. if yes, should we really always return all signatures? considering the name of the function is to recover N signatures

### CODE REVIEW

**Comment by kopy-kat** [comment]
1. imo yes bc we should preserve this check:
```solidity
if (validSigCount < requiredSignatures) revert InvalidSignature();
```

2. yeah I guess the question is do we return all signers or only valid ones; I'm leaning towards the latter but wdyt

**Comment by highskore** [comment]
> 1. imo yes bc we should preserve this check:
> 
> ```solidity
> if (validSigCount < requiredSignatures) revert InvalidSignature();
> ```
> 
> 2. yeah I guess the question is do we return all signers or only valid ones; I'm leaning towards the latter but wdyt

1. this check didn't exist before though, I added it because otherwise the param would be kind of useless lol

2. yeah makes sense to return all of them

**Comment by kopy-kat** [comment]
Lgtm

**Comment by highskore** [comment]
> Lgtm 

@zeroknots good to merge?

**Pull request merged**
